version: '3'
services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: dotnet-backend
    ports:
      - 5240:5240
    tty: true
    volumes:
      - ./projects:/projects
    working_dir: /projects
