version: '3'
services:
  app:
    image: openjdk:17
    container_name: spring-boot-bff
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./projects:/projects
    working_dir: /projects
