# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generateImageService_pb2 as generateImageService__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in generateImageService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerateImageServiceStub(object):
    """画像生成サービス
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.generateImage = channel.unary_unary(
                '/generateImageService.GenerateImageService/generateImage',
                request_serializer=generateImageService__pb2.EmptyRequest.SerializeToString,
                response_deserializer=generateImageService__pb2.ImageFile.FromString,
                _registered_method=True)


class GenerateImageServiceServicer(object):
    """画像生成サービス
    """

    def generateImage(self, request, context):
        """画像生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'generateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.generateImage,
                    request_deserializer=generateImageService__pb2.EmptyRequest.FromString,
                    response_serializer=generateImageService__pb2.ImageFile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generateImageService.GenerateImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generateImageService.GenerateImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerateImageService(object):
    """画像生成サービス
    """

    @staticmethod
    def generateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generateImageService.GenerateImageService/generateImage',
            generateImageService__pb2.EmptyRequest.SerializeToString,
            generateImageService__pb2.ImageFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
