# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generateImageService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'generateImageService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agenerateImageService.proto\x12\x14generateImageService\"\x0e\n\x0c\x45mptyRequest\"1\n\tImageFile\x12\x0f\n\x07\x43ontent\x18\x01 \x01(\t\x12\x13\n\x0b\x43ontentType\x18\x02 \x01(\t2l\n\x14GenerateImageService\x12T\n\rgenerateImage\x12\".generateImageService.EmptyRequest\x1a\x1f.generateImageService.ImageFileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generateImageService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=52
  _globals['_EMPTYREQUEST']._serialized_end=66
  _globals['_IMAGEFILE']._serialized_start=68
  _globals['_IMAGEFILE']._serialized_end=117
  _globals['_GENERATEIMAGESERVICE']._serialized_start=119
  _globals['_GENERATEIMAGESERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
